export const LoginActionType = Object.freeze({
    FETCH_LOGIN_REQUEST: "@@FILES/FETCH_LOGIN_REQUEST",
    FETCH_LOGIN_SUCCESS: "@@FILES/FETCH_LOGIN_SUCCESS",
    FETCH_LOGIN_FAILURE: "@@FILES/FETCH_LOGIN_FAILURE",
  });